import Vue from 'vue'
import {
  Form,
  Button,
  Field,
  Icon,
  Area,
  Popup,
  Cell,
  CellGroup,
  Tabbar,
  TabbarItem,
  List,
  PullRefresh,
  Divider,
  Uploader,
  RadioGroup,
  Radio,
  DropdownMenu,
  DropdownItem,
  Search,
  Checkbox,
  CheckboxGroup,
  Col,
  Row,
  Tab,
  Tabs,
  Stepper,
  DatetimePicker,
  Swipe,
  SwipeItem,
  Switch
} from 'vant'
Vue.use(Form)
Vue.use(Button)
Vue.use(Field)
Vue.use(Icon)
Vue.use(Area)
Vue.use(Popup)
Vue.use(CellGroup)
Vue.use(Cell)
Vue.use(Tabbar)
Vue.use(TabbarItem)
Vue.use(List)
Vue.use(PullRefresh)
Vue.use(Divider)
Vue.use(Uploader)
Vue.use(RadioGroup)
Vue.use(Radio)
Vue.use(DropdownMenu)
Vue.use(DropdownItem)
Vue.use(Search)
Vue.use(Checkbox)
Vue.use(CheckboxGroup)
Vue.use(Col)
Vue.use(Row)
Vue.use(Tab)
Vue.use(Tabs)
Vue.use(Stepper)
Vue.use(DatetimePicker)
Vue.use(Swipe)
Vue.use(SwipeItem)
Vue.use(Switch)
